### ISSUE TITLE
:sparkles: [Initialization] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by banssss** [korea-snorkeling-point/snorkeling-point-server#1]
### :sparkles: Issue
- Group : `server`
- Type : `add`
- Detail : 프로젝트 초기 설정

### :sparkles: Todo
1. 폴더구조 및 에러메시지 설정 추가
2. CORS 관련 설정 추가

### :sparkles: Estimated time
> `1h`

**Comment by hyejineee** [comment]
오오오🥳🥳🥳🥳
